name: Mise à jour tdmrep.json

on:
  push:
    paths:
      - '**/*.mp3'
      - '**/*.json'
      - '**/*.html'
      - '**/*.md'
      - '**/*.js'
  schedule:
    - cron: '0 12 * * *' # Exécute tous les jours à 12h UTC (14h en été en France)
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installer les dépendances
        run: npm install

      - name: Lancer le script de mise à jour
        run: node update-tdmrep.js

      - name: Commit et push des modifications
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add tdmrep.json
          git commit -m "Mise à jour automatique de tdmrep.json"
          git push
